spring:
  application:
    name: melodic-bridge

  datasource:
    url: jdbc:h2:file:./local;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    filter:
      chain:
        - pattern: "/h2-console/**"
          authorization: permitAll  # H2 콘솔 경로에 대한 접근 허용
    csrf:
      enabled: false  # CSRF 보호 비활성화
    headers:
      frame:
        options: disable  # X-Frame-Options 헤더 비활성화

  jwt:
    secret: ${JWT_SECRET_KEY}